//
// Created by 孙万捷 on 16/5/19.
//

#ifndef SUNVOLUMERENDER_COMMON_H
#define SUNVOLUMERENDER_COMMON_H

#define WIDTH 640
#define HEIGHT 640

#define MAX_LIGHT_SOURCES 8

#endif //SUNVOLUMERENDER_COMMON_H
